version: "3.10"

services:
  plants-database:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_DB=plants
      - POSTGRES_USER=plants
      - POSTGRES_PASSWORD=pass
    ports:
      - "5431:5432"
